name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Grant execute permission for gradlew
      run: chmod +x mobile/gradlew
    - name: Setup Environment
      run: ./mobile/gradlew prepareKotlinBuildScriptModel
    - name: Setup Environment
      run: ./mobile/gradlew init
    - name: Setup Environment
      run: ./mobile/gradlew wrapper
    - name: Build debug Apk
      run: ./mobile/gradlew buildNeeded --stacktrace --scan
    - name: Upload Apk
      uses: actions/upload-artifact@v1
      with:
        name: app
        path: /mobile/app/build/outputs/apk/debug/app-debug.apk
